### ISSUE TITLE
Set up Team Kanban Board

### ISSUE THREAD

**Issue by wwwdrt** [wwwdrt/react-rtk-group-project#22]
:link: https://github.com/users/wwwdrt/projects/7

Team Size: 3 
Members: DRT, Ahmed, and Rahman.

**Comment by Ibizugbe** [comment]
Hi @wwwdrt 👋👋👋, 

![tryagain](https://github.com/wwwdrt/react-rtk-group-project/assets/64643995/537f8119-89ac-47f8-8b0c-b54a8352465b)


Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights✅✅

- [x] An issue has been opened with the link to the project board and the number of students in the group.👍
- [x] Tasks have been assigned points in the board👍.


## Required Changes ♻️

- [ ] For a group of 3, you should have 24 tasks in total or 24 cards😉. Kindly take a look at [the template](https://github.com/microverseinc/curriculum-react-redux/projects/1) that was assigned to you and add the missing cards👍.
- [ ] Kindly ensure to assign tasks to each of your team member equally as required😉. when this is done, the image of the person assigned will be shown in that task card👍. take a look at the image below for reference😉.
<img width="835" alt="image" src="https://github.com/wwwdrt/react-rtk-group-project/assets/64643995/9409a465-7445-4d36-9f63-1229d09eb5e2">

<img width="372" alt="assigned_card" src="https://github.com/wwwdrt/react-rtk-group-project/assets/64643995/6eb97c9e-c189-4b6d-9b19-412e082f4238">


_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
